version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      HOST: '0.0.0.0'
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: nest
      MQTT_URL: mqtt://mqtt-broker:1883
    depends_on:
      - database
      - mqtt-broker

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database-persisted-data:/var/lib/postgresql/data

  mqtt-broker:
    image: emqx/emqx:latest
    ports:
      - '1883:1883'
      - '18083:18083'

volumes:
  pgdata:
